name: Unit tests CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # # Trigger at midnight everyday
  # schedule:
  #   - cron: '59 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.7.3"
      - uses: julia-actions/julia-buildpkg@master
      - run: julia --project=. test.jl
